export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COMPANY_UPDATING = "COMPANY_UPDATING";
export const COMPANY_UPDATE_SUCCESS = "COMPANY_UPDATE_SUCCESS";
export const COMPANY_UPDATE_FAIL = "COMPANY_UPDATE_FAIL";
    
export const JOB_UPDATING = "JOB_UPDATING";
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS";
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL";

export const RESULT_UPDATING = "RESULT_UPDATING";
export const RESULT_UPDATE_SUCCESS = "RESULT_UPDATE_SUCCESS";
export const RESULT_UPDATE_FAIL = "RESULT_UPDATE_FAIL";
export const RESULT_ADD_CLEAR = "RESULT_ADD_CLEAR";
export const RESULT_ADD_SUCCESS = "RESULT_ADD_SUCCESS";
export const RESULT_ADD_FAIL = "RESULT_ADD_FAIL";
export const RESULT_EDIT_CLEAR = "RESULT_EDIT_CLEAR";
export const RESULT_EDIT_SUCCESS = "RESULT_EDIT_SUCCESS";
export const RESULT_EDIT_FAIL = "RESULT_EDIT_FAIL";
export const RESULT_DELETE_CLEAR = "RESULT_DELETE_CLEAR";
export const RESULT_DELETE_SUCCESS = "RESULT_DELETE_SUCCESS";
export const RESULT_DELETE_FAIL = "RESULT_DELETE_FAIL";