export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const COMPANY_UPDATING = "COMPANY_UPDATING";
export const COMPANY_UPDATE_SUCCESS = "COMPANY_UPDATE_SUCCESS";
export const COMPANY_UPDATE_FAIL = "COMPANY_UPDATE_FAIL";
export const COMPANY_ADD_CLEAR = "COMPANY_ADD_CLEAR";
export const COMPANY_ADD_SUCCESS = "COMPANY_ADD_SUCCESS";
export const COMPANY_ADD_FAIL = "COMPANY_ADD_FAIL";

export const JOB_UPDATING = "JOB_UPDATING";
export const JOB_UPDATE_SUCCESS = "JOB_UPDATE_SUCCESS";
export const JOB_UPDATE_FAIL = "JOB_UPDATE_FAIL";
export const JOB_ADD_CLEAR = "JOB_ADD_CLEAR";
export const JOB_ADD_SUCCESS = "JOB_ADD_SUCCESS";
export const JOB_ADD_FAIL = "JOB_ADD_FAIL";
export const JOB_EDIT_CLEAR = "JOB_EDIT_CLEAR";
export const JOB_EDIT_SUCCESS = "JOB_EDIT_SUCCESS";
export const JOB_EDIT_FAIL = "JOB_EDIT_FAIL";
export const JOB_DELETE_CLEAR = "JOB_DELETE_CLEAR";
export const JOB_DELETE_SUCCESS = "JOB_DELETE_SUCCESS";
export const JOB_DELETE_FAIL = "JOB_DELETE_FAIL";

export const RESULT_UPDATING = "RESULT_UPDATING";
export const RESULT_UPDATE_SUCCESS = "RESULT_UPDATE_SUCCESS";
export const RESULT_UPDATE_FAIL = "RESULT_UPDATE_FAIL";
export const RESULT_ADD_CLEAR = "RESULT_ADD_CLEAR";
export const RESULT_ADD_SUCCESS = "RESULT_ADD_SUCCESS";
export const RESULT_ADD_FAIL = "RESULT_ADD_FAIL";
export const RESULT_EDIT_CLEAR = "RESULT_EDIT_CLEAR";
export const RESULT_EDIT_SUCCESS = "RESULT_EDIT_SUCCESS";
export const RESULT_EDIT_FAIL = "RESULT_EDIT_FAIL";
export const RESULT_DELETE_CLEAR = "RESULT_DELETE_CLEAR";
export const RESULT_DELETE_SUCCESS = "RESULT_DELETE_SUCCESS";
export const RESULT_DELETE_FAIL = "RESULT_DELETE_FAIL";

export const REGISTRATION_UPDATING = "REGISTRATIONS_LOADING";
export const REGISTRATION_UPDATE_SUCCESS = "REGISTRATION_UPDATE_SUCCESS";
export const REGISTRATION_UPDATE_FAIL = "REGISTRATION_UPDATE_FAIL";
export const REGISTRATION_ADD_CLEAR = "REGISTRATION_ADD_CLEAR";
export const REGISTRATION_ADD_SUCCESS = "REGISTRATION_ADD_SUCCESS";
export const REGISTRATION_ADD_FAIL = "REGISTRATION_ADD_FAIL";
export const REGISTRATION_DELETE_CLEAR = "REGISTRATION_DELETE_CLEAR";
export const REGISTRATION_DELETE_SUCCESS = "REGISTRATION_DELETE_SUCCESS";
export const REGISTRATION_DELETE_FAIL = "REGISTRATION_DELETE_FAIL";
export const REGISTRATION_MESSAGE_CLEAR = "REGISTRATION_MESSAGE_CLEAR";

export const STUDENT_UPDATING = "STUDENT_UPDATING";
export const STUDENT_UPDATE_SUCCESS = "STUDENT_UPDATE_SUCCESS";
export const STUDENT_UPDATE_FAIL = "STUDENT_UPDATE_FAIL";